name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [main] # or 'master' if that's your main branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x" # or 7.0.x / 6.0.x depending on your app

      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release -o build

      - name: Add .nojekyll
        run: touch build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
